apiVersion: v1
kind: Namespace
metadata:
  name: web-lab
spec: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: private-node-web
  labels:
    run: private-node-web
  namespace: web-lab
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: private-node-web
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: private-node-web
      namespace: web-lab
    spec:
      replicas: 5
      selector:
        matchLabels:
          run: private-node-web
      template:
        metadata:
          labels:
            run: private-node-web
        spec:
          containers:
          - image: panupongdeve/private-node-web:latest
            name: private-node-web
            imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: public-node-web
  namespace: web-lab
  labels:
    run: public-node-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: public-node-web
  type: NodePort
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: public-node-web
      namespace: web-lab
      labels:
        run: public-node-web
    spec:
      replicas: 5
      selector:
        matchLabels:
          run: public-node-web
      template:
        metadata:
          labels:
            run: public-node-web
        spec:
          containers:
          - image: panupongdeve/public-node-web:latest
            name: public-node-web
            imagePullPolicy: Always
    